"""Mock data for the LineupCast API."""

MANCHESTER_RED_PLAYERS = [
    {
        "number": 1,
        "name": "A. Keeper",
        "position": "GK",
        "role": "Goalkeeper",
        "age": 28,
        "nationality": "England",
        "recentRating": 7.1,
        "xGLast5": 0.0,
        "shotsLast5": 0,
        "assistsLast5": 0,
        "foulsPer90": 0.3,
        "yellowCardsLast10": 0,
        "vaepAttack": 0.01,
        "vaepDefense": 0.82,
        "commentaryNote": "Reliable shot-stopper, commands the box well on set pieces.",
        "coordinates": {"x": 5, "y": 50},
    },
    {
        "number": 2,
        "name": "L. Wing",
        "position": "RB",
        "role": "Right Back",
        "age": 25,
        "nationality": "Portugal",
        "recentRating": 7.3,
        "xGLast5": 0.1,
        "shotsLast5": 2,
        "assistsLast5": 2,
        "foulsPer90": 1.2,
        "yellowCardsLast10": 2,
        "vaepAttack": 0.35,
        "vaepDefense": 0.68,
        "commentaryNote": "Overlapping runs are a key outlet; watch for early crosses.",
        "coordinates": {"x": 25, "y": 85},
    },
    {
        "number": 3,
        "name": "N. Cross",
        "position": "LB",
        "role": "Left Back",
        "age": 30,
        "nationality": "France",
        "recentRating": 7.0,
        "xGLast5": 0.2,
        "shotsLast5": 3,
        "assistsLast5": 0,
        "foulsPer90": 0.9,
        "yellowCardsLast10": 1,
        "vaepAttack": 0.12,
        "vaepDefense": 0.91,
        "commentaryNote": "Aerial dominance; dangerous on corners at the near post.",
        "coordinates": {"x": 25, "y": 15},
    },
    {
        "number": 4,
        "name": "M. Stone",
        "position": "CB",
        "role": "Centre Back",
        "age": 27,
        "nationality": "Netherlands",
        "recentRating": 6.9,
        "xGLast5": 0.1,
        "shotsLast5": 1,
        "assistsLast5": 0,
        "foulsPer90": 1.1,
        "yellowCardsLast10": 3,
        "vaepAttack": 0.08,
        "vaepDefense": 0.87,
        "commentaryNote": "Ball-playing defender; look for diagonal switches to the wings.",
        "coordinates": {"x": 20, "y": 40},
    },
    {
        "number": 5,
        "name": "R. Block",
        "position": "CB",
        "role": "Centre Back",
        "age": 26,
        "nationality": "Spain",
        "recentRating": 7.2,
        "xGLast5": 0.0,
        "shotsLast5": 1,
        "assistsLast5": 1,
        "foulsPer90": 1.4,
        "yellowCardsLast10": 3,
        "vaepAttack": 0.28,
        "vaepDefense": 0.72,
        "commentaryNote": "Aggressive tackler who likes to join the attack; card risk.",
        "coordinates": {"x": 20, "y": 60},
    },
    {
        "number": 6,
        "name": "D. Tempo",
        "position": "DM",
        "role": "Defensive Midfielder",
        "age": 29,
        "nationality": "Germany",
        "recentRating": 7.4,
        "xGLast5": 0.3,
        "shotsLast5": 4,
        "assistsLast5": 1,
        "foulsPer90": 1.6,
        "yellowCardsLast10": 2,
        "vaepAttack": 0.22,
        "vaepDefense": 0.78,
        "commentaryNote": "Dictates tempo from deep; watch for late runs into the box.",
        "coordinates": {"x": 40, "y": 50},
    },
    {
        "number": 7,
        "name": "C. Press",
        "position": "DM",
        "role": "Defensive Midfielder",
        "age": 24,
        "nationality": "Brazil",
        "recentRating": 7.5,
        "xGLast5": 0.4,
        "shotsLast5": 6,
        "assistsLast5": 2,
        "foulsPer90": 1.8,
        "yellowCardsLast10": 4,
        "vaepAttack": 0.41,
        "vaepDefense": 0.55,
        "commentaryNote": "Box-to-box energy; high pressing trigger, needs to watch fouls.",
        "coordinates": {"x": 45, "y": 35},
    },
    {
        "number": 8,
        "name": "J. Spark",
        "position": "RW",
        "role": "Right Winger",
        "age": 23,
        "nationality": "Senegal",
        "recentRating": 7.8,
        "xGLast5": 0.8,
        "shotsLast5": 10,
        "assistsLast5": 1,
        "foulsPer90": 0.7,
        "yellowCardsLast10": 1,
        "vaepAttack": 0.67,
        "vaepDefense": 0.18,
        "commentaryNote": "Electric pace on the counter; favourite to score first.",
        "coordinates": {"x": 65, "y": 85},
    },
    {
        "number": 10,
        "name": "B. Vision",
        "position": "AM",
        "role": "Attacking Midfielder",
        "age": 27,
        "nationality": "Argentina",
        "recentRating": 7.9,
        "xGLast5": 0.5,
        "shotsLast5": 7,
        "assistsLast5": 4,
        "foulsPer90": 0.6,
        "yellowCardsLast10": 0,
        "vaepAttack": 0.72,
        "vaepDefense": 0.25,
        "commentaryNote": "Creative hub; unlocks defences with through balls and set pieces.",
        "coordinates": {"x": 65, "y": 50},
    },
    {
        "number": 11,
        "name": "K. Burst",
        "position": "LW",
        "role": "Left Winger",
        "age": 22,
        "nationality": "Nigeria",
        "recentRating": 7.6,
        "xGLast5": 0.6,
        "shotsLast5": 8,
        "assistsLast5": 2,
        "foulsPer90": 0.5,
        "yellowCardsLast10": 0,
        "vaepAttack": 0.58,
        "vaepDefense": 0.15,
        "commentaryNote": "Direct dribbler who cuts inside; loves the far-post curler.",
        "coordinates": {"x": 65, "y": 15},
    },
    {
        "number": 9,
        "name": "V. Finish",
        "position": "ST",
        "role": "Striker",
        "age": 26,
        "nationality": "Uruguay",
        "recentRating": 8.1,
        "xGLast5": 1.2,
        "shotsLast5": 14,
        "assistsLast5": 0,
        "foulsPer90": 0.8,
        "yellowCardsLast10": 1,
        "vaepAttack": 0.85,
        "vaepDefense": 0.08,
        "commentaryNote": "Clinical finisher; top scorer candidate, thrives on crosses.",
        "coordinates": {"x": 85, "y": 50},
    },
]

SHANGHAI_HARBOR_PLAYERS = [
    {
        "number": 1,
        "name": "W. Shield",
        "position": "GK",
        "role": "Goalkeeper",
        "age": 31,
        "nationality": "China",
        "recentRating": 6.8,
        "xGLast5": 0.0,
        "shotsLast5": 0,
        "assistsLast5": 0,
        "foulsPer90": 0.2,
        "yellowCardsLast10": 0,
        "vaepAttack": 0.01,
        "vaepDefense": 0.75,
        "commentaryNote": "Experienced keeper; strong on penalties but vulnerable to long shots.",
        "coordinates": {"x": 95, "y": 50},
    },
    {
        "number": 2,
        "name": "Z. Flank",
        "position": "RB",
        "role": "Right Back",
        "age": 27,
        "nationality": "China",
        "recentRating": 6.7,
        "xGLast5": 0.0,
        "shotsLast5": 1,
        "assistsLast5": 1,
        "foulsPer90": 1.3,
        "yellowCardsLast10": 2,
        "vaepAttack": 0.20,
        "vaepDefense": 0.62,
        "commentaryNote": "Solid defensively but limited going forward.",
        "coordinates": {"x": 75, "y": 15},
    },
    {
        "number": 5,
        "name": "H. Wall",
        "position": "CB",
        "role": "Centre Back",
        "age": 29,
        "nationality": "South Korea",
        "recentRating": 6.9,
        "xGLast5": 0.1,
        "shotsLast5": 2,
        "assistsLast5": 0,
        "foulsPer90": 1.0,
        "yellowCardsLast10": 2,
        "vaepAttack": 0.09,
        "vaepDefense": 0.80,
        "commentaryNote": "Commanding presence; organises the back line.",
        "coordinates": {"x": 80, "y": 60},
    },
    {
        "number": 4,
        "name": "J. Anchor",
        "position": "CB",
        "role": "Centre Back",
        "age": 32,
        "nationality": "China",
        "recentRating": 6.6,
        "xGLast5": 0.0,
        "shotsLast5": 1,
        "assistsLast5": 0,
        "foulsPer90": 1.2,
        "yellowCardsLast10": 3,
        "vaepAttack": 0.05,
        "vaepDefense": 0.76,
        "commentaryNote": "Veteran leader; reads the game well but lacks pace.",
        "coordinates": {"x": 80, "y": 40},
    },
    {
        "number": 3,
        "name": "L. Edge",
        "position": "LB",
        "role": "Left Back",
        "age": 24,
        "nationality": "Japan",
        "recentRating": 6.8,
        "xGLast5": 0.1,
        "shotsLast5": 2,
        "assistsLast5": 1,
        "foulsPer90": 1.1,
        "yellowCardsLast10": 1,
        "vaepAttack": 0.24,
        "vaepDefense": 0.65,
        "commentaryNote": "Willing runner; offers width in the 4-3-3 system.",
        "coordinates": {"x": 75, "y": 85},
    },
    {
        "number": 6,
        "name": "D. Anchor",
        "position": "CDM",
        "role": "Defensive Midfielder",
        "age": 28,
        "nationality": "Australia",
        "recentRating": 7.0,
        "xGLast5": 0.2,
        "shotsLast5": 3,
        "assistsLast5": 0,
        "foulsPer90": 1.7,
        "yellowCardsLast10": 3,
        "vaepAttack": 0.15,
        "vaepDefense": 0.74,
        "commentaryNote": "Shield of the defence; card risk from cynical fouls.",
        "coordinates": {"x": 60, "y": 50},
    },
    {
        "number": 8,
        "name": "M. Rhythm",
        "position": "CM",
        "role": "Central Midfielder",
        "age": 25,
        "nationality": "Brazil",
        "recentRating": 7.1,
        "xGLast5": 0.3,
        "shotsLast5": 5,
        "assistsLast5": 2,
        "foulsPer90": 0.9,
        "yellowCardsLast10": 1,
        "vaepAttack": 0.38,
        "vaepDefense": 0.50,
        "commentaryNote": "Technically gifted; links midfield and attack smoothly.",
        "coordinates": {"x": 55, "y": 35},
    },
    {
        "number": 10,
        "name": "P. Orchid",
        "position": "CM",
        "role": "Central Midfielder",
        "age": 30,
        "nationality": "Argentina",
        "recentRating": 7.3,
        "xGLast5": 0.4,
        "shotsLast5": 6,
        "assistsLast5": 3,
        "foulsPer90": 0.7,
        "yellowCardsLast10": 0,
        "vaepAttack": 0.50,
        "vaepDefense": 0.42,
        "commentaryNote": "Playmaker who sets the tempo; dangerous from distance.",
        "coordinates": {"x": 55, "y": 65},
    },
    {
        "number": 7,
        "name": "H. Counter",
        "position": "RW",
        "role": "Right Winger",
        "age": 23,
        "nationality": "Nigeria",
        "recentRating": 7.4,
        "xGLast5": 0.7,
        "shotsLast5": 9,
        "assistsLast5": 1,
        "foulsPer90": 0.6,
        "yellowCardsLast10": 1,
        "vaepAttack": 0.60,
        "vaepDefense": 0.12,
        "commentaryNote": "Lightning quick on the break; primary counter-attack threat.",
        "coordinates": {"x": 35, "y": 15},
    },
    {
        "number": 11,
        "name": "S. Late",
        "position": "LW",
        "role": "Left Winger",
        "age": 26,
        "nationality": "Colombia",
        "recentRating": 7.0,
        "xGLast5": 0.5,
        "shotsLast5": 7,
        "assistsLast5": 2,
        "foulsPer90": 1.0,
        "yellowCardsLast10": 2,
        "vaepAttack": 0.45,
        "vaepDefense": 0.20,
        "commentaryNote": "Tricky dribbler; prone to late challenges that risk cards.",
        "coordinates": {"x": 35, "y": 85},
    },
    {
        "number": 9,
        "name": "T. Marksman",
        "position": "ST",
        "role": "Striker",
        "age": 28,
        "nationality": "Italy",
        "recentRating": 7.2,
        "xGLast5": 0.9,
        "shotsLast5": 12,
        "assistsLast5": 0,
        "foulsPer90": 0.9,
        "yellowCardsLast10": 1,
        "vaepAttack": 0.72,
        "vaepDefense": 0.06,
        "commentaryNote": "Poacher instinct; excellent movement in the box.",
        "coordinates": {"x": 15, "y": 50},
    },
]

MATCH_DEMO = {
    "matchId": "demo-manchester-red-vs-shanghai-harbor",
    "competition": "Super Club Friendly",
    "kickoff": "demo",
    "status": "scheduled",
    "homeTeam": {
        "teamId": "manchester-red",
        "name": "Manchester Red",
        "shortName": "RED",
        "crest": None,
    },
    "awayTeam": {
        "teamId": "shanghai-harbor",
        "name": "Shanghai Harbor",
        "shortName": "SHA",
        "crest": None,
    },
    "score": None,
}

TEAMS = {
    "manchester-red": {
        "teamId": "manchester-red",
        "name": "Manchester Red",
        "shortName": "RED",
        "crest": None,
        "founded": 1878,
        "venue": "Red Arena",
        "league": "Super Club Friendly",
    },
    "shanghai-harbor": {
        "teamId": "shanghai-harbor",
        "name": "Shanghai Harbor",
        "shortName": "SHA",
        "crest": None,
        "founded": 2005,
        "venue": "Harbour Stadium",
        "league": "Super Club Friendly",
    },
}

PLAYERS_DB = {}

for p in MANCHESTER_RED_PLAYERS:
    key = f"manchester-red-{p['name'].replace(' ', '-').replace('.', '').lower()}"
    PLAYERS_DB[key] = {**p, "teamId": "manchester-red"}

for p in SHANGHAI_HARBOR_PLAYERS:
    key = f"shanghai-harbor-{p['name'].replace(' ', '-').replace('.', '').lower()}"
    PLAYERS_DB[key] = {**p, "teamId": "shanghai-harbor"}

LINEUPS = {
    "demo-manchester-red-vs-shanghai-harbor": {
        "matchId": "demo-manchester-red-vs-shanghai-harbor",
        "home": {
            "teamId": "manchester-red",
            "teamName": "Manchester Red",
            "formation": "4-2-3-1",
            "players": MANCHESTER_RED_PLAYERS,
        },
        "away": {
            "teamId": "shanghai-harbor",
            "teamName": "Shanghai Harbor",
            "formation": "4-3-3",
            "players": SHANGHAI_HARBOR_PLAYERS,
        },
    }
}

PREDICTION = {
    "matchId": "demo-manchester-red-vs-shanghai-harbor",
    "homeWin": 48,
    "draw": 27,
    "awayWin": 25,
    "expectedHomeGoals": 1.6,
    "expectedAwayGoals": 1.2,
    "confidence": 0.72,
    "models": [
        {
            "name": "Dixon-Coles Time-Weighted Poisson",
            "version": "1.0.0",
            "reference": "docs/model-cards/dixon-coles.md",
        },
        {
            "name": "Player Rating Adjustment",
            "version": "1.0.0",
            "reference": "docs/model-cards/player-rating-adjustment.md",
        },
        {
            "name": "xG Share Model",
            "version": "1.0.0",
            "reference": "docs/model-cards/xg-share.md",
        },
        {
            "name": "VAEP-inspired Player Impact",
            "version": "1.0.0",
            "reference": "docs/model-cards/player-rating-adjustment.md",
        },
        {
            "name": "Expected Booking xB-inspired Model",
            "version": "1.0.0",
            "reference": "docs/model-cards/xb-inspired-card-risk.md",
        },
    ],
    "inputFeatures": [
        "home_attack_strength",
        "away_defense_strength",
        "time_weighted_recent_goals",
        "home_advantage",
        "lineup_integrity",
        "player_recent_rating",
        "player_xG_last_5",
        "shots_last_5",
        "fouls_per_90",
        "yellow_cards_last_10",
        "referee_cards_per_match",
    ],
    "goalScorers": [
        {"player": "V. Finish", "team": "Manchester Red", "probability": 34},
        {"player": "J. Spark", "team": "Manchester Red", "probability": 22},
        {"player": "K. Burst", "team": "Manchester Red", "probability": 18},
        {"player": "H. Counter", "team": "Shanghai Harbor", "probability": 17},
    ],
    "cardRisks": [
        {"player": "C. Press", "team": "Manchester Red", "yellowRisk": 42, "redRisk": "low"},
        {"player": "R. Block", "team": "Manchester Red", "yellowRisk": 31, "redRisk": "low"},
        {"player": "D. Anchor", "team": "Shanghai Harbor", "yellowRisk": 38, "redRisk": "low"},
        {"player": "S. Late", "team": "Shanghai Harbor", "yellowRisk": 9, "redRisk": "low"},
    ],
    "explanations": [
        "Dixon-Coles time-weighted Poisson estimates 1.6 vs 1.2 expected goals from attack, defense, recent score trend and home advantage.",
        "Player Rating Adjustment lifts Manchester Red slightly because B. Vision, V. Finish and J. Spark are confirmed starters with strong recent ratings.",
        "xG Share ranks V. Finish first because starter minutes, central-forward position, recent xG, shot volume and penalty priority combine to the highest scorer score.",
        "Expected Booking xB-inspired risk puts C. Press and D. Anchor high because defensive midfield roles, fouls per 90 and opponent dribble threat raise yellow-card risk.",
        "Simple Red Card Risk only reports low, medium or high. S. Late remains low and no precise red-card probability is exposed.",
    ],
}

PROVIDERS = [
    {
        "id": "mock-provider",
        "name": "Mock Provider",
        "type": "mock",
        "description": "Deterministic demo data for Manchester Red vs Shanghai Harbor. No commercial sports data or API key required.",
        "status": "connected",
    },
    {
        "id": "openfootball",
        "name": "OpenFootball Adapter placeholder",
        "type": "open-data",
        "description": "Adapter interface placeholder for OpenFootball-style fixtures and team metadata.",
        "status": "placeholder",
    },
    {
        "id": "statsbomb-open-data",
        "name": "StatsBomb Open Data Adapter placeholder",
        "type": "open-data",
        "description": "Adapter interface placeholder for StatsBomb Open Data examples and event schema mapping.",
        "status": "placeholder",
    },
    {
        "id": "football-data-org",
        "name": "football-data.org Adapter placeholder",
        "type": "external-api",
        "description": "User-configured API key placeholder. Tokens are read from environment variables and must not be committed.",
        "status": "needs-token",
    },
    {
        "id": "sportmonks",
        "name": "Sportmonks Adapter placeholder",
        "type": "external-api",
        "description": "Commercial provider integration placeholder for users with their own authorized Sportmonks credentials.",
        "status": "needs-token",
    },
    {
        "id": "api-football",
        "name": "API-FOOTBALL Adapter placeholder",
        "type": "external-api",
        "description": "Commercial provider integration placeholder for users with their own authorized API-FOOTBALL credentials.",
        "status": "needs-token",
    },
]
