// @lineupcast/ai-script — Chinese example fixture for testing

import type { ScriptInput } from "../types";

/**
 * 2024-25 英超：利物浦 vs 阿森纳
 * 完整的 ScriptInput 示例数据，用于测试和文档。
 */
export const EXAMPLE_INPUT: ScriptInput = {
  match: {
    id: "match-20250511-liv-ars",
    homeTeamId: "team-liverpool",
    awayTeamId: "team-arsenal",
    kickoff: "2025-05-11T16:30:00Z",
    league: "英超",
    status: "scheduled",
  },

  lineups: {
    matchId: "match-20250511-liv-ars",
    home: {
      teamId: "team-liverpool",
      teamName: "利物浦",
      formation: "4-3-3",
      players: [
        {
          number: 1,
          name: "Alisson",
          position: "GK",
          role: "首发门将",
          age: 32,
          nationality: "巴西",
          recentRating: 7.2,
          xGLast5: 0,
          shotsLast5: 0,
          assistsLast5: 0,
          foulsPer90: 0.1,
          yellowCardsLast10: 0,
          vaepAttack: 0,
          vaepDefense: 0.8,
          commentaryNote: "世界级门将，反应极快",
          coordinates: { x: 5, y: 50 },
        },
        {
          number: 4,
          name: "Van Dijk",
          position: "CB",
          role: "后防核心",
          age: 33,
          nationality: "荷兰",
          recentRating: 7.5,
          xGLast5: 0.3,
          shotsLast5: 3,
          assistsLast5: 0,
          foulsPer90: 0.8,
          yellowCardsLast10: 2,
          vaepAttack: 0.1,
          vaepDefense: 1.2,
          commentaryNote: "空中统治力极强",
          coordinates: { x: 20, y: 40 },
        },
        {
          number: 66,
          name: "Alexander-Arnold",
          position: "DF",
          role: "右后卫/组织核心",
          age: 26,
          nationality: "英格兰",
          recentRating: 7.8,
          xGLast5: 0.5,
          shotsLast5: 5,
          assistsLast5: 3,
          foulsPer90: 0.6,
          yellowCardsLast10: 1,
          vaepAttack: 0.9,
          vaepDefense: 0.6,
          commentaryNote: "传球视野顶级，进攻利器",
          coordinates: { x: 30, y: 85 },
        },
        {
          number: 10,
          name: "Mac Allister",
          position: "CM",
          role: "中场发动机",
          age: 25,
          nationality: "阿根廷",
          recentRating: 7.6,
          xGLast5: 0.6,
          shotsLast5: 7,
          assistsLast5: 2,
          foulsPer90: 1.2,
          yellowCardsLast10: 3,
          vaepAttack: 0.7,
          vaepDefense: 0.5,
          commentaryNote: "攻守转换枢纽",
          coordinates: { x: 50, y: 50 },
        },
        {
          number: 11,
          name: "Salah",
          position: "FW",
          role: "锋线核心",
          age: 32,
          nationality: "埃及",
          recentRating: 8.1,
          xGLast5: 1.8,
          shotsLast5: 14,
          assistsLast5: 2,
          foulsPer90: 0.5,
          yellowCardsLast10: 1,
          vaepAttack: 1.5,
          vaepDefense: 0.2,
          commentaryNote: "进球效率极高，右路内切威胁大",
          coordinates: { x: 80, y: 70 },
        },
        {
          number: 9,
          name: "Núñez",
          position: "ST",
          role: "中锋",
          age: 25,
          nationality: "乌拉圭",
          recentRating: 7.0,
          xGLast5: 1.2,
          shotsLast5: 11,
          assistsLast5: 1,
          foulsPer90: 0.9,
          yellowCardsLast10: 2,
          vaepAttack: 1.1,
          vaepDefense: 0.1,
          commentaryNote: "冲击力强，跑位积极",
          coordinates: { x: 85, y: 50 },
        },
      ],
    },
    away: {
      teamId: "team-arsenal",
      teamName: "阿森纳",
      formation: "4-3-3",
      players: [
        {
          number: 22,
          name: "Raya",
          position: "GK",
          role: "首发门将",
          age: 29,
          nationality: "西班牙",
          recentRating: 7.3,
          xGLast5: 0,
          shotsLast5: 0,
          assistsLast5: 0,
          foulsPer90: 0.1,
          yellowCardsLast10: 0,
          vaepAttack: 0,
          vaepDefense: 0.7,
          commentaryNote: "脚下技术出色，出球能力强",
          coordinates: { x: 95, y: 50 },
        },
        {
          number: 6,
          name: "Gabriel",
          position: "CB",
          role: "后防中坚",
          age: 26,
          nationality: "巴西",
          recentRating: 7.4,
          xGLast5: 0.4,
          shotsLast5: 4,
          assistsLast5: 0,
          foulsPer90: 1.0,
          yellowCardsLast10: 3,
          vaepAttack: 0.2,
          vaepDefense: 1.1,
          commentaryNote: "定位球得分威胁大",
          coordinates: { x: 80, y: 40 },
        },
        {
          number: 5,
          name: "Rice",
          position: "CM",
          role: "中场屏障",
          age: 26,
          nationality: "英格兰",
          recentRating: 7.9,
          xGLast5: 0.7,
          shotsLast5: 8,
          assistsLast5: 2,
          foulsPer90: 1.1,
          yellowCardsLast10: 2,
          vaepAttack: 0.6,
          vaepDefense: 0.9,
          commentaryNote: "覆盖面广，远射有威胁",
          coordinates: { x: 50, y: 50 },
        },
        {
          number: 7,
          name: "Saka",
          position: "FW",
          role: "右路核心",
          age: 23,
          nationality: "英格兰",
          recentRating: 8.3,
          xGLast5: 1.6,
          shotsLast5: 12,
          assistsLast5: 3,
          foulsPer90: 0.7,
          yellowCardsLast10: 1,
          vaepAttack: 1.4,
          vaepDefense: 0.3,
          commentaryNote: "突破犀利，创造力顶级",
          coordinates: { x: 75, y: 80 },
        },
        {
          number: 29,
          name: "Havertz",
          position: "ST",
          role: "伪九号",
          age: 25,
          nationality: "德国",
          recentRating: 7.4,
          xGLast5: 1.0,
          shotsLast5: 9,
          assistsLast5: 1,
          foulsPer90: 0.8,
          yellowCardsLast10: 2,
          vaepAttack: 0.9,
          vaepDefense: 0.3,
          commentaryNote: "战术灵活，串联能力强",
          coordinates: { x: 80, y: 50 },
        },
      ],
    },
  },

  prediction: {
    matchId: "match-20250511-liv-ars",
    homeWin: 0.45,
    draw: 0.26,
    awayWin: 0.29,
    expectedHomeGoals: 1.6,
    expectedAwayGoals: 1.2,
    confidence: "medium",
  },

  goalScorers: [
    { player: "Salah", team: "利物浦", probability: 42 },
    { player: "Saka", team: "阿森纳", probability: 35 },
    { player: "Núñez", team: "利物浦", probability: 28 },
    { player: "Havertz", team: "阿森纳", probability: 25 },
    { player: "Mac Allister", team: "利物浦", probability: 18 },
  ],

  cardRisks: [
    { player: "Mac Allister", team: "利物浦", yellowRisk: 38, redRisk: 3 },
    { player: "Gabriel", team: "阿森纳", yellowRisk: 35, redRisk: 4 },
    { player: "Rice", team: "阿森纳", yellowRisk: 28, redRisk: 2 },
  ],

  style: "professional",
  duration: "3min",
};

/**
 * Pre-generated expected output for the example input (professional / 3min).
 * Used in snapshot/golden-file tests.
 */
export const EXAMPLE_OUTPUT_OPENING_SNIPPET = "利物浦主场迎战阿森纳";
export const EXAMPLE_OUTPUT_PREDICTION_SNIPPET = "45%";
export const EXAMPLE_OUTPUT_MODEL_SOURCE = "根据 Dixon-Coles 与阵容修正模型";
