import type { Player, Match, Prediction, DataProvider, H2HRecord, FormEntry, League } from "./types";

export const manchesterRedXI: Player[] = [
  {
    id: "keeper",
    number: 1,
    name: "A. Keeper",
    position: "GK",
    role: "Goalkeeper",
    age: 28,
    nationality: "ENG",
    recentRating: 7.2,
    xGLast5: 0,
    shotsLast5: 0,
    assistsLast5: 0,
    foulsPer90: 0.3,
    yellowCardsLast10: 0,
    redCardsLast10: 0,
    vaepAttack: 0.02,
    vaepDefense: 0.85,
    commentaryNote: "稳定发挥，扑救成功率高达78%，是后防线的定海神针。",
    x: 50,
    y: 92,
  },
  {
    id: "wing-rb",
    number: 2,
    name: "L. Wing",
    position: "RB",
    role: "Right Back",
    age: 25,
    nationality: "BRA",
    recentRating: 7.0,
    xGLast5: 0.3,
    shotsLast5: 3,
    assistsLast5: 2,
    foulsPer90: 1.2,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.45,
    vaepDefense: 0.62,
    commentaryNote: "攻守兼备的右后卫，助攻能力突出，是边路进攻的重要发起点。",
    x: 82,
    y: 75,
  },
  {
    id: "cross-lb",
    number: 3,
    name: "N. Cross",
    position: "LB",
    role: "Left Back",
    age: 27,
    nationality: "FRA",
    recentRating: 6.8,
    xGLast5: 0.2,
    shotsLast5: 2,
    assistsLast5: 3,
    foulsPer90: 1.0,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.38,
    vaepDefense: 0.58,
    commentaryNote: "左路传中精准，是定位球战术的关键执行者。",
    x: 18,
    y: 75,
  },
  {
    id: "stone-cb",
    number: 4,
    name: "M. Stone",
    position: "CB",
    role: "Centre Back",
    age: 30,
    nationality: "ENG",
    recentRating: 7.4,
    xGLast5: 0.5,
    shotsLast5: 4,
    assistsLast5: 0,
    foulsPer90: 0.8,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.15,
    vaepDefense: 0.88,
    commentaryNote: "中后卫核心，头球争顶能力出色，定位球进攻中的重要武器。",
    x: 60,
    y: 78,
  },
  {
    id: "block-cb",
    number: 5,
    name: "R. Block",
    position: "CB",
    role: "Centre Back",
    age: 26,
    nationality: "GER",
    recentRating: 7.1,
    xGLast5: 0.2,
    shotsLast5: 2,
    assistsLast5: 0,
    foulsPer90: 1.4,
    yellowCardsLast10: 3,
    redCardsLast10: 0,
    vaepAttack: 0.1,
    vaepDefense: 0.82,
    commentaryNote: "防守硬朗，但犯规偏多需要注意纪律问题。",
    x: 40,
    y: 78,
  },
  {
    id: "tempo-dm",
    number: 6,
    name: "D. Tempo",
    position: "DM",
    role: "Defensive Midfielder",
    age: 29,
    nationality: "ESP",
    recentRating: 7.3,
    xGLast5: 0.4,
    shotsLast5: 5,
    assistsLast5: 1,
    foulsPer90: 1.6,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.32,
    vaepDefense: 0.71,
    commentaryNote: "中场节拍器，掌控比赛节奏，拦截能力出色。",
    x: 50,
    y: 58,
  },
  {
    id: "press-dm",
    number: 7,
    name: "C. Press",
    position: "DM",
    role: "Defensive Midfielder",
    age: 24,
    nationality: "NED",
    recentRating: 6.9,
    xGLast5: 0.3,
    shotsLast5: 4,
    assistsLast5: 2,
    foulsPer90: 2.1,
    yellowCardsLast10: 4,
    redCardsLast10: 0,
    vaepAttack: 0.28,
    vaepDefense: 0.65,
    commentaryNote: "拼抢积极但犯规频繁，需要控制情绪避免吃牌。",
    x: 50,
    y: 48,
  },
  {
    id: "spark-rw",
    number: 8,
    name: "J. Spark",
    position: "RW",
    role: "Right Winger",
    age: 23,
    nationality: "POR",
    recentRating: 7.6,
    xGLast5: 1.2,
    shotsLast5: 12,
    assistsLast5: 2,
    foulsPer90: 0.8,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.78,
    vaepDefense: 0.15,
    commentaryNote: "速度型边锋，突破能力极强，近期状态火热，进球效率高。",
    x: 78,
    y: 32,
  },
  {
    id: "vision-am",
    number: 9,
    name: "B. Vision",
    position: "AM",
    role: "Attacking Midfielder",
    age: 27,
    nationality: "ARG",
    recentRating: 7.8,
    xGLast5: 0.8,
    shotsLast5: 8,
    assistsLast5: 4,
    foulsPer90: 0.6,
    yellowCardsLast10: 0,
    redCardsLast10: 0,
    vaepAttack: 0.82,
    vaepDefense: 0.25,
    commentaryNote: "组织核心，传球视野开阔，是球队进攻的发动机。",
    x: 50,
    y: 35,
  },
  {
    id: "burst-lw",
    number: 10,
    name: "K. Burst",
    position: "LW",
    role: "Left Winger",
    age: 22,
    nationality: "NGA",
    recentRating: 7.4,
    xGLast5: 0.9,
    shotsLast5: 10,
    assistsLast5: 1,
    foulsPer90: 0.7,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.72,
    vaepDefense: 0.12,
    commentaryNote: "爆发力强，内切射门威胁大，是左路的主要攻击点。",
    x: 22,
    y: 32,
  },
  {
    id: "finish-st",
    number: 11,
    name: "V. Finish",
    position: "ST",
    role: "Striker",
    age: 26,
    nationality: "URU",
    recentRating: 7.7,
    xGLast5: 1.8,
    shotsLast5: 15,
    assistsLast5: 1,
    foulsPer90: 0.9,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.91,
    vaepDefense: 0.08,
    commentaryNote: "高效射手，门前嗅觉灵敏，是球队的头号得分手。",
    x: 50,
    y: 15,
  },
];

export const currentMatch: Match = {
  id: "match-001",
  homeTeam: "Manchester Red",
  awayTeam: "Shanghai Harbor",
  kickoff: "2026-05-06T20:00:00Z",
  venue: "Red Stadium",
  status: "upcoming",
};

export const matchPrediction: Prediction = {
  homeWin: 48,
  draw: 27,
  awayWin: 25,
  expectedHomeGoals: 1.6,
  expectedAwayGoals: 1.2,
  confidence: 72,
  possibleScorers: [
    { name: "V. Finish", probability: 34 },
    { name: "J. Spark", probability: 22 },
    { name: "K. Burst", probability: 18 },
    { name: "H. Counter", probability: 17 },
  ],
  yellowCardRisks: [
    { name: "C. Press", risk: 42 },
    { name: "D. Anchor", risk: 38 },
    { name: "R. Block", risk: 31 },
  ],
  redCardRisks: [{ name: "S. Late", risk: 8 }],
};

export const dataProviders: DataProvider[] = [
  {
    id: "mock",
    name: "Mock Provider",
    status: "connected",
    lastSync: "2026-05-06T19:00:00Z",
    fields: ["lineup", "stats", "fixtures"],
    errorCount: 0,
    lastError: null,
    lastSuccessfulSync: "2026-05-06T19:00:00Z",
    health: "healthy",
  },
  {
    id: "openfootball",
    name: "OpenFootball",
    status: "disconnected",
    lastSync: null,
    fields: ["fixtures", "standings"],
    errorCount: 0,
    lastError: null,
    lastSuccessfulSync: null,
    health: "healthy",
  },
  {
    id: "statsbomb",
    name: "StatsBomb Open Data",
    status: "connected",
    lastSync: "2026-05-06T18:30:00Z",
    fields: ["events", "lineup", "freeframes"],
    errorCount: 0,
    lastError: null,
    lastSuccessfulSync: "2026-05-06T18:30:00Z",
    health: "healthy",
  },
  {
    id: "football-data",
    name: "football-data.org",
    status: "error",
    lastSync: "2026-05-05T10:00:00Z",
    fields: ["fixtures", "standings", "scorers"],
    errorCount: 3,
    lastError: "HTTP 401 Unauthorized: API token missing or expired. Configure FOOTBALL_DATA_TOKEN in environment.",
    lastSuccessfulSync: "2026-05-05T10:00:00Z",
    health: "degraded",
  },
  {
    id: "sportmonks",
    name: "Sportmonks",
    status: "disconnected",
    lastSync: null,
    fields: ["fixtures", "lineup", "stats", "odds"],
    errorCount: 1,
    lastError: "Connection refused: Sportmonks API endpoint unreachable. Check SPORTMONKS_API_KEY.",
    lastSuccessfulSync: null,
    health: "unhealthy",
  },
  {
    id: "api-football",
    name: "API-FOOTBALL",
    status: "connected",
    lastSync: "2026-05-06T19:15:00Z",
    fields: ["fixtures", "lineup", "stats", "events"],
    errorCount: 2,
    lastError: "HTTP 403 Forbidden: Invalid API key. Verify API_FOOTBALL_KEY credentials.",
    lastSuccessfulSync: "2026-05-06T19:15:00Z",
    health: "degraded",
  },
];

export const trendData = [
  { match: "MD28", rating: 7.1, xG: 1.4, result: "W" },
  { match: "MD29", rating: 6.8, xG: 0.9, result: "L" },
  { match: "MD30", rating: 7.4, xG: 1.8, result: "W" },
  { match: "MD31", rating: 7.0, xG: 1.2, result: "D" },
  { match: "MD32", rating: 7.3, xG: 1.6, result: "W" },
];

export const h2hRecord: H2HRecord = {
  matches: [
    { date: "2026-04-12", homeTeam: "Manchester Red", awayTeam: "Shanghai Harbor", homeScore: 2, awayScore: 1, venue: "Red Stadium", competition: "Club Friendly" },
    { date: "2025-11-20", homeTeam: "Shanghai Harbor", awayTeam: "Manchester Red", homeScore: 1, awayScore: 1, venue: "Harbor Arena", competition: "Club Friendly" },
    { date: "2025-07-08", homeTeam: "Manchester Red", awayTeam: "Shanghai Harbor", homeScore: 3, awayScore: 0, venue: "Red Stadium", competition: "Summer Cup" },
    { date: "2025-02-15", homeTeam: "Shanghai Harbor", awayTeam: "Manchester Red", homeScore: 2, awayScore: 2, venue: "Harbor Arena", competition: "Club Friendly" },
    { date: "2024-12-01", homeTeam: "Manchester Red", awayTeam: "Shanghai Harbor", homeScore: 1, awayScore: 0, venue: "Red Stadium", competition: "Winter Trophy" },
    { date: "2024-08-18", homeTeam: "Shanghai Harbor", awayTeam: "Manchester Red", homeScore: 0, awayScore: 2, venue: "Harbor Arena", competition: "Club Friendly" },
  ],
  homeWins: 3,
  draws: 2,
  awayWins: 1,
  homeGoals: 9,
  awayGoals: 4,
};

export const homeForm: FormEntry[] = [
  { matchId: "f1", date: "2026-04-28", opponent: "London Blues", isHome: true, result: "W", goalsFor: 2, goalsAgainst: 0, xG: 1.8, xGA: 0.6, venue: "Red Stadium" },
  { matchId: "f2", date: "2026-04-21", opponent: "Berlin Eagles", isHome: false, result: "W", goalsFor: 3, goalsAgainst: 1, xG: 2.1, xGA: 1.2, venue: "Eagle Arena" },
  { matchId: "f3", date: "2026-04-14", opponent: "Madrid Lions", isHome: true, result: "W", goalsFor: 1, goalsAgainst: 0, xG: 1.4, xGA: 0.8, venue: "Red Stadium" },
  { matchId: "f4", date: "2026-04-07", opponent: "Paris Stars", isHome: false, result: "D", goalsFor: 1, goalsAgainst: 1, xG: 1.1, xGA: 1.3, venue: "Star Park" },
  { matchId: "f5", date: "2026-03-30", opponent: "Milan Knights", isHome: true, result: "L", goalsFor: 0, goalsAgainst: 2, xG: 0.9, xGA: 1.7, venue: "Red Stadium" },
  { matchId: "f6", date: "2026-03-23", opponent: "Rome Wolves", isHome: false, result: "W", goalsFor: 2, goalsAgainst: 1, xG: 1.6, xGA: 0.9, venue: "Wolf Den" },
  { matchId: "f7", date: "2026-03-16", opponent: "Amsterdam Oranges", isHome: true, result: "D", goalsFor: 2, goalsAgainst: 2, xG: 1.9, xGA: 1.5, venue: "Red Stadium" },
  { matchId: "f8", date: "2026-03-09", opponent: "Lisbon Waves", isHome: false, result: "W", goalsFor: 1, goalsAgainst: 0, xG: 1.2, xGA: 0.7, venue: "Wave Stadium" },
];

export const awayForm: FormEntry[] = [
  { matchId: "af1", date: "2026-04-27", opponent: "Beijing Dragons", isHome: true, result: "W", goalsFor: 3, goalsAgainst: 1, xG: 2.4, xGA: 1.0, venue: "Harbor Arena" },
  { matchId: "af2", date: "2026-04-20", opponent: "Guangzhou Tigers", isHome: false, result: "D", goalsFor: 1, goalsAgainst: 1, xG: 1.2, xGA: 1.1, venue: "Tiger Stadium" },
  { matchId: "af3", date: "2026-04-13", opponent: "Shenzhen Phoenix", isHome: true, result: "W", goalsFor: 2, goalsAgainst: 0, xG: 1.9, xGA: 0.5, venue: "Harbor Arena" },
  { matchId: "af4", date: "2026-04-06", opponent: "Chengdu Pandas", isHome: false, result: "L", goalsFor: 0, goalsAgainst: 1, xG: 0.8, xGA: 1.4, venue: "Panda Park" },
  { matchId: "af5", date: "2026-03-30", opponent: "Wuhan Warriors", isHome: true, result: "W", goalsFor: 4, goalsAgainst: 2, xG: 3.1, xGA: 1.8, venue: "Harbor Arena" },
  { matchId: "af6", date: "2026-03-23", opponent: "Tianjin Lions", isHome: false, result: "D", goalsFor: 0, goalsAgainst: 0, xG: 0.6, xGA: 0.9, venue: "Lion Den" },
  { matchId: "af7", date: "2026-03-16", opponent: "Dalian Whales", isHome: true, result: "W", goalsFor: 2, goalsAgainst: 1, xG: 1.7, xGA: 1.2, venue: "Harbor Arena" },
  { matchId: "af8", date: "2026-03-09", opponent: "Hangzhou Leopards", isHome: false, result: "W", goalsFor: 1, goalsAgainst: 0, xG: 1.0, xGA: 0.8, venue: "Leopard Ground" },
];

export const leagues: League[] = [
  { id: "premier-league", name: "Premier League", shortName: "EPL", country: "England", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", season: "2025-26", isActive: true },
  { id: "la-liga", name: "La Liga", shortName: "LL", country: "Spain", countryFlag: "🇪🇸", season: "2025-26", isActive: true },
  { id: "bundesliga", name: "Bundesliga", shortName: "BL", country: "Germany", countryFlag: "🇩🇪", season: "2025-26", isActive: true },
  { id: "serie-a", name: "Serie A", shortName: "SA", country: "Italy", countryFlag: "🇮🇹", season: "2025-26", isActive: true },
  { id: "ligue-1", name: "Ligue 1", shortName: "L1", country: "France", countryFlag: "🇫🇷", season: "2025-26", isActive: true },
  { id: "chinese-super-league", name: "Chinese Super League", shortName: "CSL", country: "China", countryFlag: "🇨🇳", season: "2025", isActive: true },
  { id: "champions-league", name: "UEFA Champions League", shortName: "UCL", country: "Europe", countryFlag: "🇪🇺", season: "2025-26", isActive: true },
];
