import type { Player, Match, Prediction, DataProvider } from "./types";

export const manchesterRedXI: Player[] = [
  {
    id: "keeper",
    number: 1,
    name: "A. Keeper",
    position: "GK",
    role: "Goalkeeper",
    age: 28,
    nationality: "ENG",
    recentRating: 7.2,
    xGLast5: 0,
    shotsLast5: 0,
    assistsLast5: 0,
    foulsPer90: 0.3,
    yellowCardsLast10: 0,
    redCardsLast10: 0,
    vaepAttack: 0.02,
    vaepDefense: 0.85,
    commentaryNote: "稳定发挥，扑救成功率高达78%，是后防线的定海神针。",
    x: 50,
    y: 92,
  },
  {
    id: "wing-rb",
    number: 2,
    name: "L. Wing",
    position: "RB",
    role: "Right Back",
    age: 25,
    nationality: "BRA",
    recentRating: 7.0,
    xGLast5: 0.3,
    shotsLast5: 3,
    assistsLast5: 2,
    foulsPer90: 1.2,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.45,
    vaepDefense: 0.62,
    commentaryNote: "攻守兼备的右后卫，助攻能力突出，是边路进攻的重要发起点。",
    x: 82,
    y: 75,
  },
  {
    id: "cross-lb",
    number: 3,
    name: "N. Cross",
    position: "LB",
    role: "Left Back",
    age: 27,
    nationality: "FRA",
    recentRating: 6.8,
    xGLast5: 0.2,
    shotsLast5: 2,
    assistsLast5: 3,
    foulsPer90: 1.0,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.38,
    vaepDefense: 0.58,
    commentaryNote: "左路传中精准，是定位球战术的关键执行者。",
    x: 18,
    y: 75,
  },
  {
    id: "stone-cb",
    number: 4,
    name: "M. Stone",
    position: "CB",
    role: "Centre Back",
    age: 30,
    nationality: "ENG",
    recentRating: 7.4,
    xGLast5: 0.5,
    shotsLast5: 4,
    assistsLast5: 0,
    foulsPer90: 0.8,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.15,
    vaepDefense: 0.88,
    commentaryNote: "中后卫核心，头球争顶能力出色，定位球进攻中的重要武器。",
    x: 60,
    y: 78,
  },
  {
    id: "block-cb",
    number: 5,
    name: "R. Block",
    position: "CB",
    role: "Centre Back",
    age: 26,
    nationality: "GER",
    recentRating: 7.1,
    xGLast5: 0.2,
    shotsLast5: 2,
    assistsLast5: 0,
    foulsPer90: 1.4,
    yellowCardsLast10: 3,
    redCardsLast10: 0,
    vaepAttack: 0.1,
    vaepDefense: 0.82,
    commentaryNote: "防守硬朗，但犯规偏多需要注意纪律问题。",
    x: 40,
    y: 78,
  },
  {
    id: "tempo-dm",
    number: 6,
    name: "D. Tempo",
    position: "DM",
    role: "Defensive Midfielder",
    age: 29,
    nationality: "ESP",
    recentRating: 7.3,
    xGLast5: 0.4,
    shotsLast5: 5,
    assistsLast5: 1,
    foulsPer90: 1.6,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.32,
    vaepDefense: 0.71,
    commentaryNote: "中场节拍器，掌控比赛节奏，拦截能力出色。",
    x: 50,
    y: 58,
  },
  {
    id: "press-dm",
    number: 7,
    name: "C. Press",
    position: "DM",
    role: "Defensive Midfielder",
    age: 24,
    nationality: "NED",
    recentRating: 6.9,
    xGLast5: 0.3,
    shotsLast5: 4,
    assistsLast5: 2,
    foulsPer90: 2.1,
    yellowCardsLast10: 4,
    redCardsLast10: 0,
    vaepAttack: 0.28,
    vaepDefense: 0.65,
    commentaryNote: "拼抢积极但犯规频繁，需要控制情绪避免吃牌。",
    x: 50,
    y: 48,
  },
  {
    id: "spark-rw",
    number: 8,
    name: "J. Spark",
    position: "RW",
    role: "Right Winger",
    age: 23,
    nationality: "POR",
    recentRating: 7.6,
    xGLast5: 1.2,
    shotsLast5: 12,
    assistsLast5: 2,
    foulsPer90: 0.8,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.78,
    vaepDefense: 0.15,
    commentaryNote: "速度型边锋，突破能力极强，近期状态火热，进球效率高。",
    x: 78,
    y: 32,
  },
  {
    id: "vision-am",
    number: 9,
    name: "B. Vision",
    position: "AM",
    role: "Attacking Midfielder",
    age: 27,
    nationality: "ARG",
    recentRating: 7.8,
    xGLast5: 0.8,
    shotsLast5: 8,
    assistsLast5: 4,
    foulsPer90: 0.6,
    yellowCardsLast10: 0,
    redCardsLast10: 0,
    vaepAttack: 0.82,
    vaepDefense: 0.25,
    commentaryNote: "组织核心，传球视野开阔，是球队进攻的发动机。",
    x: 50,
    y: 35,
  },
  {
    id: "burst-lw",
    number: 10,
    name: "K. Burst",
    position: "LW",
    role: "Left Winger",
    age: 22,
    nationality: "NGA",
    recentRating: 7.4,
    xGLast5: 0.9,
    shotsLast5: 10,
    assistsLast5: 1,
    foulsPer90: 0.7,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.72,
    vaepDefense: 0.12,
    commentaryNote: "爆发力强，内切射门威胁大，是左路的主要攻击点。",
    x: 22,
    y: 32,
  },
  {
    id: "finish-st",
    number: 11,
    name: "V. Finish",
    position: "ST",
    role: "Striker",
    age: 26,
    nationality: "URU",
    recentRating: 7.7,
    xGLast5: 1.8,
    shotsLast5: 15,
    assistsLast5: 1,
    foulsPer90: 0.9,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.91,
    vaepDefense: 0.08,
    commentaryNote: "高效射手，门前嗅觉灵敏，是球队的头号得分手。",
    x: 50,
    y: 15,
  },
];

export const currentMatch: Match = {
  id: "match-001",
  homeTeam: "Manchester Red",
  awayTeam: "Shanghai Harbor",
  kickoff: "2026-05-06T20:00:00Z",
  venue: "Red Stadium",
  status: "upcoming",
};

export const matchPrediction: Prediction = {
  homeWin: 48,
  draw: 27,
  awayWin: 25,
  expectedHomeGoals: 1.6,
  expectedAwayGoals: 1.2,
  confidence: 72,
  possibleScorers: [
    { name: "V. Finish", probability: 34 },
    { name: "J. Spark", probability: 22 },
    { name: "K. Burst", probability: 18 },
    { name: "H. Counter", probability: 17 },
  ],
  yellowCardRisks: [
    { name: "C. Press", risk: 42 },
    { name: "D. Anchor", risk: 38 },
    { name: "R. Block", risk: 31 },
  ],
  redCardRisks: [{ name: "S. Late", risk: 8 }],
};

export const dataProviders: DataProvider[] = [
  {
    id: "mock",
    name: "Mock Provider",
    status: "connected",
    lastSync: "2026-05-06T19:00:00Z",
    fields: ["lineup", "stats", "fixtures"],
  },
  {
    id: "openfootball",
    name: "OpenFootball",
    status: "disconnected",
    lastSync: null,
    fields: ["fixtures", "standings"],
  },
  {
    id: "statsbomb",
    name: "StatsBomb Open Data",
    status: "connected",
    lastSync: "2026-05-06T18:30:00Z",
    fields: ["events", "lineup", "freeframes"],
  },
  {
    id: "football-data",
    name: "football-data.org",
    status: "error",
    lastSync: "2026-05-05T10:00:00Z",
    fields: ["fixtures", "standings", "scorers"],
  },
  {
    id: "sportmonks",
    name: "Sportmonks",
    status: "disconnected",
    lastSync: null,
    fields: ["fixtures", "lineup", "stats", "odds"],
  },
  {
    id: "api-football",
    name: "API-FOOTBALL",
    status: "connected",
    lastSync: "2026-05-06T19:15:00Z",
    fields: ["fixtures", "lineup", "stats", "events"],
  },
];

export const trendData = [
  { match: "MD28", rating: 7.1, xG: 1.4, result: "W" },
  { match: "MD29", rating: 6.8, xG: 0.9, result: "L" },
  { match: "MD30", rating: 7.4, xG: 1.8, result: "W" },
  { match: "MD31", rating: 7.0, xG: 1.2, result: "D" },
  { match: "MD32", rating: 7.3, xG: 1.6, result: "W" },
];
