import type { Player, Match, Prediction, DataProvider, H2HRecord, FormEntry, League, SeasonStats } from "./types";

export const manchesterRedXI: Player[] = [
  {
    id: "keeper",
    number: 1,
    name: "A. Keeper",
    position: "GK",
    role: "Goalkeeper",
    age: 28,
    nationality: "ENG",
    recentRating: 7.2,
    xGLast5: 0,
    shotsLast5: 0,
    assistsLast5: 0,
    foulsPer90: 0.3,
    yellowCardsLast10: 0,
    redCardsLast10: 0,
    vaepAttack: 0.02,
    vaepDefense: 0.85,
    commentaryNote: "稳定发挥，扑救成功率高达78%，是后防线的定海神针。",
    x: 50,
    y: 92,
  },
  {
    id: "wing-rb",
    number: 2,
    name: "L. Wing",
    position: "RB",
    role: "Right Back",
    age: 25,
    nationality: "BRA",
    recentRating: 7.0,
    xGLast5: 0.3,
    shotsLast5: 3,
    assistsLast5: 2,
    foulsPer90: 1.2,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.45,
    vaepDefense: 0.62,
    commentaryNote: "攻守兼备的右后卫，助攻能力突出，是边路进攻的重要发起点。",
    x: 82,
    y: 75,
  },
  {
    id: "cross-lb",
    number: 3,
    name: "N. Cross",
    position: "LB",
    role: "Left Back",
    age: 27,
    nationality: "FRA",
    recentRating: 6.8,
    xGLast5: 0.2,
    shotsLast5: 2,
    assistsLast5: 3,
    foulsPer90: 1.0,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.38,
    vaepDefense: 0.58,
    commentaryNote: "左路传中精准，是定位球战术的关键执行者。",
    x: 18,
    y: 75,
  },
  {
    id: "stone-cb",
    number: 4,
    name: "M. Stone",
    position: "CB",
    role: "Centre Back",
    age: 30,
    nationality: "ENG",
    recentRating: 7.4,
    xGLast5: 0.5,
    shotsLast5: 4,
    assistsLast5: 0,
    foulsPer90: 0.8,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.15,
    vaepDefense: 0.88,
    commentaryNote: "中后卫核心，头球争顶能力出色，定位球进攻中的重要武器。",
    x: 60,
    y: 78,
  },
  {
    id: "block-cb",
    number: 5,
    name: "R. Block",
    position: "CB",
    role: "Centre Back",
    age: 26,
    nationality: "GER",
    recentRating: 7.1,
    xGLast5: 0.2,
    shotsLast5: 2,
    assistsLast5: 0,
    foulsPer90: 1.4,
    yellowCardsLast10: 3,
    redCardsLast10: 0,
    vaepAttack: 0.1,
    vaepDefense: 0.82,
    commentaryNote: "防守硬朗，但犯规偏多需要注意纪律问题。",
    x: 40,
    y: 78,
  },
  {
    id: "tempo-dm",
    number: 6,
    name: "D. Tempo",
    position: "DM",
    role: "Defensive Midfielder",
    age: 29,
    nationality: "ESP",
    recentRating: 7.3,
    xGLast5: 0.4,
    shotsLast5: 5,
    assistsLast5: 1,
    foulsPer90: 1.6,
    yellowCardsLast10: 2,
    redCardsLast10: 0,
    vaepAttack: 0.32,
    vaepDefense: 0.71,
    commentaryNote: "中场节拍器，掌控比赛节奏，拦截能力出色。",
    x: 50,
    y: 58,
  },
  {
    id: "press-dm",
    number: 7,
    name: "C. Press",
    position: "DM",
    role: "Defensive Midfielder",
    age: 24,
    nationality: "NED",
    recentRating: 6.9,
    xGLast5: 0.3,
    shotsLast5: 4,
    assistsLast5: 2,
    foulsPer90: 2.1,
    yellowCardsLast10: 4,
    redCardsLast10: 0,
    vaepAttack: 0.28,
    vaepDefense: 0.65,
    commentaryNote: "拼抢积极但犯规频繁，需要控制情绪避免吃牌。",
    x: 50,
    y: 48,
  },
  {
    id: "spark-rw",
    number: 8,
    name: "J. Spark",
    position: "RW",
    role: "Right Winger",
    age: 23,
    nationality: "POR",
    recentRating: 7.6,
    xGLast5: 1.2,
    shotsLast5: 12,
    assistsLast5: 2,
    foulsPer90: 0.8,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.78,
    vaepDefense: 0.15,
    commentaryNote: "速度型边锋，突破能力极强，近期状态火热，进球效率高。",
    x: 78,
    y: 32,
  },
  {
    id: "vision-am",
    number: 9,
    name: "B. Vision",
    position: "AM",
    role: "Attacking Midfielder",
    age: 27,
    nationality: "ARG",
    recentRating: 7.8,
    xGLast5: 0.8,
    shotsLast5: 8,
    assistsLast5: 4,
    foulsPer90: 0.6,
    yellowCardsLast10: 0,
    redCardsLast10: 0,
    vaepAttack: 0.82,
    vaepDefense: 0.25,
    commentaryNote: "组织核心，传球视野开阔，是球队进攻的发动机。",
    x: 50,
    y: 35,
  },
  {
    id: "burst-lw",
    number: 10,
    name: "K. Burst",
    position: "LW",
    role: "Left Winger",
    age: 22,
    nationality: "NGA",
    recentRating: 7.4,
    xGLast5: 0.9,
    shotsLast5: 10,
    assistsLast5: 1,
    foulsPer90: 0.7,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.72,
    vaepDefense: 0.12,
    commentaryNote: "爆发力强，内切射门威胁大，是左路的主要攻击点。",
    x: 22,
    y: 32,
  },
  {
    id: "finish-st",
    number: 11,
    name: "V. Finish",
    position: "ST",
    role: "Striker",
    age: 26,
    nationality: "URU",
    recentRating: 7.7,
    xGLast5: 1.8,
    shotsLast5: 15,
    assistsLast5: 1,
    foulsPer90: 0.9,
    yellowCardsLast10: 1,
    redCardsLast10: 0,
    vaepAttack: 0.91,
    vaepDefense: 0.08,
    commentaryNote: "高效射手，门前嗅觉灵敏，是球队的头号得分手。",
    x: 50,
    y: 15,
  },
];

export const currentMatch: Match = {
  id: "match-001",
  homeTeam: "Manchester Red",
  awayTeam: "Shanghai Harbor",
  kickoff: "2026-05-06T20:00:00Z",
  venue: "Red Stadium",
  status: "upcoming",
};

export const matchPrediction: Prediction = {
  homeWin: 48,
  draw: 27,
  awayWin: 25,
  expectedHomeGoals: 1.6,
  expectedAwayGoals: 1.2,
  confidence: 72,
  possibleScorers: [
    { name: "V. Finish", probability: 34 },
    { name: "J. Spark", probability: 22 },
    { name: "K. Burst", probability: 18 },
    { name: "H. Counter", probability: 17 },
  ],
  yellowCardRisks: [
    { name: "C. Press", risk: 42 },
    { name: "D. Anchor", risk: 38 },
    { name: "R. Block", risk: 31 },
  ],
  redCardRisks: [{ name: "S. Late", risk: 8 }],
};

export const dataProviders: DataProvider[] = [
  {
    id: "mock",
    name: "Mock Provider",
    status: "connected",
    lastSync: "2026-05-06T19:00:00Z",
    fields: ["lineup", "stats", "fixtures"],
    errorCount: 0,
    lastError: null,
    lastSuccessfulSync: "2026-05-06T19:00:00Z",
    health: "healthy",
  },
  {
    id: "openfootball",
    name: "OpenFootball",
    status: "disconnected",
    lastSync: null,
    fields: ["fixtures", "standings"],
    errorCount: 0,
    lastError: null,
    lastSuccessfulSync: null,
    health: "healthy",
  },
  {
    id: "statsbomb",
    name: "StatsBomb Open Data",
    status: "connected",
    lastSync: "2026-05-06T18:30:00Z",
    fields: ["events", "lineup", "freeframes"],
    errorCount: 0,
    lastError: null,
    lastSuccessfulSync: "2026-05-06T18:30:00Z",
    health: "healthy",
  },
  {
    id: "football-data",
    name: "football-data.org",
    status: "error",
    lastSync: "2026-05-05T10:00:00Z",
    fields: ["fixtures", "standings", "scorers"],
    errorCount: 3,
    lastError: "HTTP 401 Unauthorized: API token missing or expired. Configure FOOTBALL_DATA_TOKEN in environment.",
    lastSuccessfulSync: "2026-05-05T10:00:00Z",
    health: "degraded",
  },
  {
    id: "sportmonks",
    name: "Sportmonks",
    status: "disconnected",
    lastSync: null,
    fields: ["fixtures", "lineup", "stats", "odds"],
    errorCount: 1,
    lastError: "Connection refused: Sportmonks API endpoint unreachable. Check SPORTMONKS_API_KEY.",
    lastSuccessfulSync: null,
    health: "unhealthy",
  },
  {
    id: "api-football",
    name: "API-FOOTBALL",
    status: "connected",
    lastSync: "2026-05-06T19:15:00Z",
    fields: ["fixtures", "lineup", "stats", "events"],
    errorCount: 2,
    lastError: "HTTP 403 Forbidden: Invalid API key. Verify API_FOOTBALL_KEY credentials.",
    lastSuccessfulSync: "2026-05-06T19:15:00Z",
    health: "degraded",
  },
];

export const trendData = [
  { match: "MD28", rating: 7.1, xG: 1.4, result: "W" },
  { match: "MD29", rating: 6.8, xG: 0.9, result: "L" },
  { match: "MD30", rating: 7.4, xG: 1.8, result: "W" },
  { match: "MD31", rating: 7.0, xG: 1.2, result: "D" },
  { match: "MD32", rating: 7.3, xG: 1.6, result: "W" },
];

export const h2hRecord: H2HRecord = {
  matches: [
    { date: "2026-04-12", homeTeam: "Manchester Red", awayTeam: "Shanghai Harbor", homeScore: 2, awayScore: 1, venue: "Red Stadium", competition: "Club Friendly" },
    { date: "2025-11-20", homeTeam: "Shanghai Harbor", awayTeam: "Manchester Red", homeScore: 1, awayScore: 1, venue: "Harbor Arena", competition: "Club Friendly" },
    { date: "2025-07-08", homeTeam: "Manchester Red", awayTeam: "Shanghai Harbor", homeScore: 3, awayScore: 0, venue: "Red Stadium", competition: "Summer Cup" },
    { date: "2025-02-15", homeTeam: "Shanghai Harbor", awayTeam: "Manchester Red", homeScore: 2, awayScore: 2, venue: "Harbor Arena", competition: "Club Friendly" },
    { date: "2024-12-01", homeTeam: "Manchester Red", awayTeam: "Shanghai Harbor", homeScore: 1, awayScore: 0, venue: "Red Stadium", competition: "Winter Trophy" },
    { date: "2024-08-18", homeTeam: "Shanghai Harbor", awayTeam: "Manchester Red", homeScore: 0, awayScore: 2, venue: "Harbor Arena", competition: "Club Friendly" },
  ],
  homeWins: 3,
  draws: 2,
  awayWins: 1,
  homeGoals: 9,
  awayGoals: 4,
};

export const homeForm: FormEntry[] = [
  { matchId: "f1", date: "2026-04-28", opponent: "London Blues", isHome: true, result: "W", goalsFor: 2, goalsAgainst: 0, xG: 1.8, xGA: 0.6, venue: "Red Stadium" },
  { matchId: "f2", date: "2026-04-21", opponent: "Berlin Eagles", isHome: false, result: "W", goalsFor: 3, goalsAgainst: 1, xG: 2.1, xGA: 1.2, venue: "Eagle Arena" },
  { matchId: "f3", date: "2026-04-14", opponent: "Madrid Lions", isHome: true, result: "W", goalsFor: 1, goalsAgainst: 0, xG: 1.4, xGA: 0.8, venue: "Red Stadium" },
  { matchId: "f4", date: "2026-04-07", opponent: "Paris Stars", isHome: false, result: "D", goalsFor: 1, goalsAgainst: 1, xG: 1.1, xGA: 1.3, venue: "Star Park" },
  { matchId: "f5", date: "2026-03-30", opponent: "Milan Knights", isHome: true, result: "L", goalsFor: 0, goalsAgainst: 2, xG: 0.9, xGA: 1.7, venue: "Red Stadium" },
  { matchId: "f6", date: "2026-03-23", opponent: "Rome Wolves", isHome: false, result: "W", goalsFor: 2, goalsAgainst: 1, xG: 1.6, xGA: 0.9, venue: "Wolf Den" },
  { matchId: "f7", date: "2026-03-16", opponent: "Amsterdam Oranges", isHome: true, result: "D", goalsFor: 2, goalsAgainst: 2, xG: 1.9, xGA: 1.5, venue: "Red Stadium" },
  { matchId: "f8", date: "2026-03-09", opponent: "Lisbon Waves", isHome: false, result: "W", goalsFor: 1, goalsAgainst: 0, xG: 1.2, xGA: 0.7, venue: "Wave Stadium" },
];

export const awayForm: FormEntry[] = [
  { matchId: "af1", date: "2026-04-27", opponent: "Beijing Dragons", isHome: true, result: "W", goalsFor: 3, goalsAgainst: 1, xG: 2.4, xGA: 1.0, venue: "Harbor Arena" },
  { matchId: "af2", date: "2026-04-20", opponent: "Guangzhou Tigers", isHome: false, result: "D", goalsFor: 1, goalsAgainst: 1, xG: 1.2, xGA: 1.1, venue: "Tiger Stadium" },
  { matchId: "af3", date: "2026-04-13", opponent: "Shenzhen Phoenix", isHome: true, result: "W", goalsFor: 2, goalsAgainst: 0, xG: 1.9, xGA: 0.5, venue: "Harbor Arena" },
  { matchId: "af4", date: "2026-04-06", opponent: "Chengdu Pandas", isHome: false, result: "L", goalsFor: 0, goalsAgainst: 1, xG: 0.8, xGA: 1.4, venue: "Panda Park" },
  { matchId: "af5", date: "2026-03-30", opponent: "Wuhan Warriors", isHome: true, result: "W", goalsFor: 4, goalsAgainst: 2, xG: 3.1, xGA: 1.8, venue: "Harbor Arena" },
  { matchId: "af6", date: "2026-03-23", opponent: "Tianjin Lions", isHome: false, result: "D", goalsFor: 0, goalsAgainst: 0, xG: 0.6, xGA: 0.9, venue: "Lion Den" },
  { matchId: "af7", date: "2026-03-16", opponent: "Dalian Whales", isHome: true, result: "W", goalsFor: 2, goalsAgainst: 1, xG: 1.7, xGA: 1.2, venue: "Harbor Arena" },
  { matchId: "af8", date: "2026-03-09", opponent: "Hangzhou Leopards", isHome: false, result: "W", goalsFor: 1, goalsAgainst: 0, xG: 1.0, xGA: 0.8, venue: "Leopard Ground" },
];

export const leagues: League[] = [
  { id: "premier-league", name: "Premier League", shortName: "EPL", country: "England", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", season: "2025-26", isActive: true },
  { id: "la-liga", name: "La Liga", shortName: "LL", country: "Spain", countryFlag: "🇪🇸", season: "2025-26", isActive: true },
  { id: "bundesliga", name: "Bundesliga", shortName: "BL", country: "Germany", countryFlag: "🇩🇪", season: "2025-26", isActive: true },
  { id: "serie-a", name: "Serie A", shortName: "SA", country: "Italy", countryFlag: "🇮🇹", season: "2025-26", isActive: true },
  { id: "ligue-1", name: "Ligue 1", shortName: "L1", country: "France", countryFlag: "🇫🇷", season: "2025-26", isActive: true },
  { id: "chinese-super-league", name: "Chinese Super League", shortName: "CSL", country: "China", countryFlag: "🇨🇳", season: "2025", isActive: true },
  { id: "champions-league", name: "UEFA Champions League", shortName: "UCL", country: "Europe", countryFlag: "🇪🇺", season: "2025-26", isActive: true },
];

export const seasonStats: SeasonStats = {
  overview: {
    leagueId: "premier-league",
    leagueName: "Premier League",
    season: "2025-26",
    totalMatches: 260,
    totalGoals: 689,
    avgGoalsPerMatch: 2.65,
    totalCleanSheets: 98,
    totalYellowCards: 1042,
    totalRedCards: 38,
    totalPenalties: 52,
    homeWinPct: 44.2,
    drawPct: 25.8,
    awayWinPct: 30.0,
  },
  topScorers: [
    { rank: 1, playerId: "scorer-1", name: "V. Finish", team: "Manchester Red", teamId: "manchester-red", goals: 24, assists: 7, matches: 32, minutesPlayed: 2780, penaltyGoals: 4, goalsPer90: 0.78 },
    { rank: 2, playerId: "scorer-2", name: "H. Counter", team: "Shanghai Harbor", teamId: "shanghai-harbor", goals: 21, assists: 5, matches: 31, minutesPlayed: 2650, penaltyGoals: 2, goalsPer90: 0.71 },
    { rank: 3, playerId: "scorer-3", name: "R. Santos", team: "London Blues", teamId: "london-blues", goals: 19, assists: 11, matches: 33, minutesPlayed: 2900, penaltyGoals: 6, goalsPer90: 0.59 },
    { rank: 4, playerId: "scorer-4", name: "M. Dubois", team: "Paris Stars", teamId: "paris-stars", goals: 18, assists: 3, matches: 30, minutesPlayed: 2520, penaltyGoals: 0, goalsPer90: 0.64 },
    { rank: 5, playerId: "scorer-5", name: "K. Burst", team: "Manchester Red", teamId: "manchester-red", goals: 16, assists: 9, matches: 32, minutesPlayed: 2680, penaltyGoals: 0, goalsPer90: 0.54 },
    { rank: 6, playerId: "scorer-6", name: "L. Martinez", team: "Madrid Lions", teamId: "madrid-lions", goals: 15, assists: 6, matches: 31, minutesPlayed: 2400, penaltyGoals: 3, goalsPer90: 0.56 },
    { rank: 7, playerId: "scorer-7", name: "J. Spark", team: "Manchester Red", teamId: "manchester-red", goals: 14, assists: 12, matches: 33, minutesPlayed: 2850, penaltyGoals: 0, goalsPer90: 0.44 },
    { rank: 8, playerId: "scorer-8", name: "T. Müller", team: "Berlin Eagles", teamId: "berlin-eagles", goals: 13, assists: 8, matches: 30, minutesPlayed: 2380, penaltyGoals: 1, goalsPer90: 0.49 },
    { rank: 9, playerId: "scorer-9", name: "A. Silva", team: "Lisbon Waves", teamId: "lisbon-waves", goals: 12, assists: 4, matches: 29, minutesPlayed: 2200, penaltyGoals: 2, goalsPer90: 0.49 },
    { rank: 10, playerId: "scorer-10", name: "D. Costa", team: "Rome Wolves", teamId: "rome-wolves", goals: 12, assists: 3, matches: 32, minutesPlayed: 2700, penaltyGoals: 0, goalsPer90: 0.40 },
  ],
  topAssists: [
    { rank: 1, playerId: "assist-1", name: "B. Vision", team: "Manchester Red", teamId: "manchester-red", assists: 14, keyPasses: 78, matches: 32, minutesPlayed: 2820, assistsPer90: 0.45 },
    { rank: 2, playerId: "assist-2", name: "J. Spark", team: "Manchester Red", teamId: "manchester-red", assists: 12, keyPasses: 65, matches: 33, minutesPlayed: 2850, assistsPer90: 0.38 },
    { rank: 3, playerId: "assist-3", name: "R. Santos", team: "London Blues", teamId: "london-blues", assists: 11, keyPasses: 72, matches: 33, minutesPlayed: 2900, assistsPer90: 0.34 },
    { rank: 4, playerId: "assist-4", name: "N. Cross", team: "Manchester Red", teamId: "manchester-red", assists: 10, keyPasses: 56, matches: 30, minutesPlayed: 2500, assistsPer90: 0.36 },
    { rank: 5, playerId: "assist-5", name: "K. Burst", team: "Manchester Red", teamId: "manchester-red", assists: 9, keyPasses: 48, matches: 32, minutesPlayed: 2680, assistsPer90: 0.30 },
    { rank: 6, playerId: "assist-6", name: "T. Müller", team: "Berlin Eagles", teamId: "berlin-eagles", assists: 8, keyPasses: 52, matches: 30, minutesPlayed: 2380, assistsPer90: 0.30 },
    { rank: 7, playerId: "assist-7", name: "L. Wing", team: "Manchester Red", teamId: "manchester-red", assists: 7, keyPasses: 42, matches: 31, minutesPlayed: 2600, assistsPer90: 0.24 },
    { rank: 8, playerId: "assist-8", name: "V. Finish", team: "Manchester Red", teamId: "manchester-red", assists: 7, keyPasses: 35, matches: 32, minutesPlayed: 2780, assistsPer90: 0.23 },
    { rank: 9, playerId: "assist-9", name: "P. Herrera", team: "Madrid Lions", teamId: "madrid-lions", assists: 7, keyPasses: 58, matches: 29, minutesPlayed: 2300, assistsPer90: 0.27 },
    { rank: 10, playerId: "assist-10", name: "F. Bianchi", team: "Milan Knights", teamId: "milan-knights", assists: 6, keyPasses: 45, matches: 31, minutesPlayed: 2450, assistsPer90: 0.22 },
  ],
  cleanSheets: [
    { rank: 1, playerId: "cs-1", name: "A. Keeper", team: "Manchester Red", teamId: "manchester-red", cleanSheets: 16, goalsConceded: 22, matches: 32, concededPer90: 0.62, savePercentage: 78.5 },
    { rank: 2, playerId: "cs-2", name: "G. Neuer II", team: "Berlin Eagles", teamId: "berlin-eagles", cleanSheets: 14, goalsConceded: 28, matches: 30, concededPer90: 0.84, savePercentage: 75.2 },
    { rank: 3, playerId: "cs-3", name: "C. Bravo Jr", team: "London Blues", teamId: "london-blues", cleanSheets: 13, goalsConceded: 30, matches: 33, concededPer90: 0.82, savePercentage: 74.1 },
    { rank: 4, playerId: "cs-4", name: "M. Donnarumma", team: "Milan Knights", teamId: "milan-knights", cleanSheets: 12, goalsConceded: 32, matches: 31, concededPer90: 0.93, savePercentage: 72.8 },
    { rank: 5, playerId: "cs-5", name: "J. Oblak Jr", team: "Madrid Lions", teamId: "madrid-lions", cleanSheets: 11, goalsConceded: 29, matches: 30, concededPer90: 0.87, savePercentage: 76.3 },
    { rank: 6, playerId: "cs-6", name: "K. Navas II", team: "Paris Stars", teamId: "paris-stars", cleanSheets: 10, goalsConceded: 35, matches: 31, concededPer90: 1.02, savePercentage: 71.5 },
    { rank: 7, playerId: "cs-7", name: "S. Patricio", team: "Rome Wolves", teamId: "rome-wolves", cleanSheets: 9, goalsConceded: 34, matches: 30, concededPer90: 1.02, savePercentage: 70.8 },
    { rank: 8, playerId: "cs-8", name: "R. Zieler", team: "Shanghai Harbor", teamId: "shanghai-harbor", cleanSheets: 9, goalsConceded: 38, matches: 32, concededPer90: 1.07, savePercentage: 69.4 },
  ],
  cardLeaders: [
    { rank: 1, playerId: "card-1", name: "R. Block", team: "Manchester Red", teamId: "manchester-red", yellowCards: 11, redCards: 1, totalCards: 12, foulsCommitted: 58, matches: 30, cardsPer90: 0.36 },
    { rank: 2, playerId: "card-2", name: "D. Anchor", team: "Manchester Red", teamId: "manchester-red", yellowCards: 10, redCards: 0, totalCards: 10, foulsCommitted: 52, matches: 28, cardsPer90: 0.32 },
    { rank: 3, playerId: "card-3", name: "C. Press", team: "Manchester Red", teamId: "manchester-red", yellowCards: 9, redCards: 1, totalCards: 10, foulsCommitted: 65, matches: 31, cardsPer90: 0.29 },
    { rank: 4, playerId: "card-4", name: "S. Ramos Jr", team: "Madrid Lions", teamId: "madrid-lions", yellowCards: 9, redCards: 2, totalCards: 11, foulsCommitted: 48, matches: 29, cardsPer90: 0.34 },
    { rank: 5, playerId: "card-5", name: "G. Pepe II", team: "Lisbon Waves", teamId: "lisbon-waves", yellowCards: 8, redCards: 1, totalCards: 9, foulsCommitted: 45, matches: 27, cardsPer90: 0.30 },
    { rank: 6, playerId: "card-6", name: "V. Kompany Jr", team: "London Blues", teamId: "london-blues", yellowCards: 8, redCards: 0, totalCards: 8, foulsCommitted: 42, matches: 32, cardsPer90: 0.23 },
    { rank: 7, playerId: "card-7", name: "N. Kante II", team: "Paris Stars", teamId: "paris-stars", yellowCards: 7, redCards: 0, totalCards: 7, foulsCommitted: 38, matches: 30, cardsPer90: 0.21 },
    { rank: 8, playerId: "card-8", name: "M. Verratti Jr", team: "Rome Wolves", teamId: "rome-wolves", yellowCards: 7, redCards: 1, totalCards: 8, foulsCommitted: 50, matches: 28, cardsPer90: 0.26 },
  ],
};
